
# BASE_URL: "http://localhost:11434/api/"
BASE_URL: "http://192.168.10.67:11434/api/"

# LLM_MODEL: "deepseek-r1:1.5b"
# LLM_MODEL: "deepseek-r1:7b"
LLM_MODEL: "deepseek-r1:14b"

# FILE PATH
company_path: "./config/company.csv"
product_path: "./config/product.csv"
product1_path: "./config/product1.csv"
rule_path: "./config/rule.csv"
